version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - npm install
  build:
    commands:
      - npm test
  reports:
  arn:aws:codebuild:eu-west-1:164748279645:report-group/cicd-test-report: #test file information
    files:
      - 'coverage/**/*'
       discard-paths: no #do not remove file paths from test result files      
artifacts:
  files:
    - 'coverage/**/*'
