version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - npm install
  build:
    commands:
      - npm test
reports:
  arn:aws:codebuild:eu-west-1:164748279645:report-group/cicd-test-report:
    files:
      - 'coverage/**/*'
    discard-paths: no     
artifacts:
  files:
    - 'coverage/**/*'
